name: Sridevi Krishnan
markdown: redcarpet
exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "preview.jpg",
  "README.md"]

theme: jekyll-theme-minimal

baseurl: "" # the subpath of your site, e.g. /blog
url: ""

